<a href="https://colab.research.google.com/github/RJuro/am-21/blob/main/2021_05_11_HA_Math_1_3_Matricer_edit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Session 3 - Matricer

Ligesom vektorer har matricer deres eget sæt af algebraiske operationer. I denne del vil vi lære om de mest centrale matrixoperationer og bygge op mod at bruge nogle af dem til at løse matrixligninger. 

#### Del 3.1
Lad os først starte med matrixaddition og subtraktion.

Hvis du husker fra sidste del om vektorer, består en matrix af en eller flere søjlevektorer.


Matrix: 
$$
\left[
  \begin{matrix}
    0.5 & 2 & 3 \\
    1.4 & 4 & 4 \\
    0.3 & 7 & 1 \\
  \end{matrix}
\right]
$$

$$
\swarrow
\downarrow
\searrow
$$ 

Søjlevektorer:

$$
\left[ \begin{array}{cc}
0.5 \\
1.4 \\
0.3
\end{array} \right]
%
\left[ \begin{array}{cc}
2 \\
4 \\
7
\end{array} \right]
%
\left[ \begin{array}{cc}
3 \\
4 \\
1
\end{array} \right]
$$

På grund af dette kan vi overføre operationerne fra vektorer også til matricer. Vi kan
udføre vektoraddition og subtraktion mellem vektorer med det samme antal rækker.
Vi kan kun udføre matrixaddition og subtraktion mellem matricer, der indeholder det samme antal rækker og kolonner. `M1.shape == M2.shape`



Valid summering:
$$
  \begin{bmatrix}
    0.5 & 2 \\
    1.4 & 4 \\
  \end{bmatrix}
+
  \begin{bmatrix}
    4 & 4 \\
    7 & 1 \\
  \end{bmatrix}
 %
 \hspace{1cm}
  \begin{bmatrix}
    0.5 & 2 \\
    7 & 1.7 \\
    2 & 5
  \end{bmatrix}
+
  \begin{bmatrix}
    0.5 & 2 \\
    7 & 1.7 \\
    2 & 5
  \end{bmatrix}
$$

No Go 🚫: 
$$
  \begin{bmatrix}
    0.5 & 3 & 5 \\
    1.4 & 3 & 9 \\
  \end{bmatrix}
+
  \begin{bmatrix}
    1 \\
    4 \\
    1
  \end{bmatrix}
$$

In [1]:
import numpy as np

In [4]:
M1 = np.array([[0.5,2],
              [1.4,4]])

M2 = np.array([[4,4],
               [7,1]])

M3 = np.array([1,4,1])

In [5]:
M1 + M2

array([[4.5, 6. ],
       [8.4, 5. ]])

In [6]:
M1 + M3

ValueError: ignored

Lige som med vektorer fungerer matrixaddition og subtraktion ved at fordele operationerne på tværs af de specifikke elementer og kombinere dem.


In [7]:
M1 = np.array([[6,2,4],[3.5,5,7],[5,3,2]])
M2 = np.array([[0, 3.4, 2],[3,0.2,1],[0.1, 1.1, 7]])

M1 + M2

array([[6. , 5.4, 6. ],
       [6.5, 5.2, 8. ],
       [5.1, 4.1, 9. ]])

$$
A + B = 
  \begin{smallmatrix} \textrm{A}\\\begin{bmatrix}
    6 & 2 & 4 \\ 
    3.5 & 5 & 7 \\ 
    5 & 3 & 2
  \end{bmatrix}\end{smallmatrix}
+
 \begin{smallmatrix} \textrm{B}\\\begin{bmatrix}
    0 & 3.4 & 2 \\
    3 & 0.2 & 1 \\
    0.1 & 1.1 & 7 \\
  \end{bmatrix}\end{smallmatrix}
=
\begin{smallmatrix} \textrm{A+B}\\\begin{bmatrix}
    6 & 5.4 & 6 \\
    6.5 & 5.2 & 8 \\
    5.1 & 4.1 & 9 \\
  \end{bmatrix}\end{smallmatrix}
$$

Endelig kan vi også multiplicere en matrix med en skalarværdi, ligesom vi kan med en vektor. 

$$
A5 =
  \hspace{1cm} \begin{smallmatrix} \textrm{A}\\5 \ * \
  \begin{bmatrix}
    6 & 2 & 4 \\ 
    3.5 & 5 & 7 \\ 
    5 & 3 & 2
  \end{bmatrix}\end{smallmatrix}
=
 \begin{smallmatrix} \textrm{A5}\\\begin{bmatrix}
    30 & 10 & 20 \\
    17.5 & 25 & 35 \\
    25 & 15 & 10 \\
  \end{bmatrix}\end{smallmatrix}
$$

In [8]:
M1 * 5

array([[30. , 10. , 20. ],
       [17.5, 25. , 35. ],
       [25. , 15. , 10. ]])

#### Del 3.2
Matrixligningen, vi diskuterede kort i den sidste mission, er et eksempel på matrix-vektor multiplikation. Når vi multiplicerer en matrix med en vektor, kombinerer vi i princippet hver række i matricen med søjlevektoren.

$$
Ac = 
  \begin{smallmatrix} \textrm{A}\\\begin{bmatrix}
    0.7 & 3 & 9 \\
    1.7 & 2 & 9 \\
    0.7 & 9 & 2 \\
  \end{bmatrix}\end{smallmatrix}
*
 \begin{smallmatrix} \textrm{c}\\\begin{bmatrix}
    1 \\
    2 \\
    1 \\
  \end{bmatrix}\end{smallmatrix}
=
\begin{smallmatrix} \textrm{A * c}\\\begin{bmatrix}
    (0.7*1) &+& (3*2) &+& (9*1) \\
    (1.7*1) &+& (2*2) &+& (9*1) \\
    (0.7*1) &+& (9*2) &+& (2*1) \\
  \end{bmatrix}\end{smallmatrix}
=
  \begin{smallmatrix} \textrm{Ac}\\\begin{bmatrix}
    15.7 \\
    14.7 \\
    20.7 \\
  \end{bmatrix}\end{smallmatrix}
$$

For at multiplicere en matrix med en vektor skal antallet af kolonner i matrixen
matche antallet af rækker i vektoren.

Valide produkter:
$$
  \begin{bmatrix}
    0.7 & 3 & 9 \\
    1.7 & 2 & 9 \\
    0.7 & 9 & 2
  \end{bmatrix}
·%
  \begin{bmatrix}
    1 \\
    2 \\
    1
  \end{bmatrix}
 %
 \hspace{1cm}
  \begin{bmatrix}
    0.7 & 3 & 9 \\
    1.7 & 2 & 9 \\
  \end{bmatrix}
·%
  \begin{bmatrix}
    1 \\
    2 \\
    1
  \end{bmatrix} 
$$


Nope! 🚫 
$$
  \begin{bmatrix}
    0.7 & 3 & 9 \\
    1.7 & 2 & 9 \\
  \end{bmatrix}
·
  \begin{bmatrix}
    1 \\
    2 \\
  \end{bmatrix}
$$

Lige som når der er 2 vektorerkan vi bruge `numpy.dot()` eller `@` til at beregne dot-product

##### **Øvelse**
Opræt følgende matrix som et NumPy-array med navnet **matrix_a**:

$$
  \begin{bmatrix}
    0.7 & 3 & 9 \\
    1.7 & 2 & 9 \\
    0.7 & 9 & 2
  \end{bmatrix}
$$

In [10]:
matrix_a = np.array([[0.7,3,9],
                     [1.7, 2, 9],
                    [0.7, 9, 2]])

Opræt følgende vektor some et NumPy-array med navnet **vector_b**:

$$
  \begin{bmatrix}
    1 \\
    2 \\
    1
  \end{bmatrix}
$$

In [20]:
vector_b = np.array([1,2,1])

Beregn dot-product og vis resultat


In [21]:
matrix_a @ vector_b

array([15.7, 14.7, 20.7])

In [13]:
np.dot(matrix_a, vector_b)

array([15.7, 14.7, 20.7])

#### Del 3.3
Som vi ded består en matrix af søjlevektorer. Vi kan derfor bruge samme koncepter, vi lærte om matrixvektormultiplikation til at multiplicere matricer sammen. I matrixvektor multiplikation udførte vi et prikprodukt mellem hver række i matrixen og søjlevektoren. I matrixmultiplikation udvider vi dette til at udføre et prikprodukt mellem hver række i den første matrix og hver kolonne i den anden matrix. 

$$
AB = 
  \begin{smallmatrix} \textrm{A}\\\begin{bmatrix}
    0.7 & 3 \\
    1.7 & 2 \\    
  \end{bmatrix}\end{smallmatrix}
·
 \begin{smallmatrix} \textrm{B}\\\begin{bmatrix}
    1 & 2\\
    2 & 3\\
  \end{bmatrix}\end{smallmatrix}
=
\begin{smallmatrix} \textrm{A * B}\\\begin{bmatrix}
    (0.7*1+3*2) & (0.7*2+3*3) \\
    (1.7*1+*2*2) & (1.7*2+2*3) \\
  \end{bmatrix}\end{smallmatrix}
=
  \begin{smallmatrix} \textrm{AB}\\\begin{bmatrix}
    6.7 & 10.4 \\
    5.7 & 9.4 \\
  \end{bmatrix}\end{smallmatrix}
$$

Som med matrixvektormultiplikation skal kolonnerne i den første matrix matche antallet af rækker i den anden matrix. 

In [22]:
A = np.array([[0.7, 3],
              [1.7 , 2]])

B = np.array([[1, 2],
              [2 , 3]])

A @ B

array([[ 6.7, 10.4],
       [ 5.7,  9.4]])

OBS: Rækkeføgen er vigtig!

$$
BA = 
  \begin{smallmatrix} \textrm{B}\\\begin{bmatrix}
    1 & 2 \\
    2 & 3 \\    
  \end{bmatrix}\end{smallmatrix}
·
 \begin{smallmatrix} \textrm{A}\\\begin{bmatrix}
    0.7 & 3\\
    1.7 & 2\\
  \end{bmatrix}\end{smallmatrix}
=
\begin{smallmatrix} \textrm{B * A}\\\begin{bmatrix}
    (1*0.7+2*1.7) & (1*3+2*2) \\
    (2*0.7+3*1.7) & (2*3+3*2) \\
  \end{bmatrix}\end{smallmatrix}
=
  \begin{smallmatrix} \textrm{BA}\\\begin{bmatrix}
    4.1 & 7 \\
    6.5 & 12 \\
  \end{bmatrix}\end{smallmatrix}
$$

For at multiplicere matricer i NumPy bruger vi den samme numpy.dot () - funktion eller @ som vi brugte i sidste del.

**Øvelse**

* Multiplicer matrix_a med matrix_b, og tildel til **product_ab**.

* Multiplicer matrix_b med matrix_a og tildel til **product_ba**. 

* Vis begge matricer. 

Er de ens? Betyder rækkefølge noget, når matricer multipliceres?


In [23]:
matrix_b = np.array([[1,2],
                     [2,3]])

matrix_a = np.array([[0.7,3],
                     [1.7,2]])

product_ab = matrix_a @ matrix_b

product_ba = matrix_b @ matrix_a

In [25]:
product_ab

array([[ 6.7, 10.4],
       [ 5.7,  9.4]])

In [26]:
product_ba

array([[ 4.1,  7. ],
       [ 6.5, 12. ]])

#### Del 3.4
Matrix transponse skifter rækker og kolonner i en matrix. Du kan tænke på transponse som en rotation. I data analytics, statistik og finance arbejdes der ofte med datatabeller i forskellige dimensioner. På grund af kravene til matrixmultiplikation skal vi nogle gange transponere en matrix så vi kan multiplicere matricer sammen, der ikke har samme antal rækker og kolonner.

En matrix transponse kunne typis se således ud: 

Matrix til transponse:
$$
  \begin{bmatrix}
    1 & 2\\
    3 & 4 \\
    5 & 6 \\
  \end{bmatrix}
$$

Transponse

$$
  \begin{bmatrix}
    1 & 3 & 5\\
    2 & 4 & 6\\
  \end{bmatrix}
$$

Matematisk bruger vi notationen $A^T$ til at skrive transponse. 

$A^T + B^T = C$

TRansponse har nogle interessante regler, der er ret intuitive. For eksempel, når vi tager transponse af summen af to matricer, kan vi distribuere transponse til hver matrix: 

$(A+B)^T = A^T + B^T$

Lidt mere kontraintuitiv er dog det at tage transponse af produktet af 2 matricer:

$(AB)^T = B^T A^T$

Lad os lige se på det ved med numpy:
Vi kan enten bruge `np.transpose()` eller bare skrive `T` efter en matrix.

In [28]:
M1

array([[6. , 2. , 4. ],
       [3.5, 5. , 7. ],
       [5. , 3. , 2. ]])

In [29]:
M1.T

array([[6. , 3.5, 5. ],
       [2. , 5. , 3. ],
       [4. , 7. , 2. ]])

In [33]:
print(M1)
print()
print(M1.T)

[[6.  2.  4. ]
 [3.5 5.  7. ]
 [5.  3.  2. ]]

[[6.  3.5 5. ]
 [2.  5.  3. ]
 [4.  7.  2. ]]


**Øvelse**

* Beregn transponse af **matrix_a** og tildel den til **transpose_a**. Vis **transpose_a** ved hjælp af funktionen print(). 

* Beregn transponse af transpose_a og vis den ved hjælp af **print()**. Matcher dette den originale matrix, **matrix_a**? 

* Multiplicer transponse af **matrix_b** med transponse af **matrix_a** (i den rækkefølge) og tildel til **trans_ba**: 

* Multiplicer transponse af **matrix_a** med transponse af **matrix_b** (i den rækkefølge) og tildel til **trans_ab**: 

* Multiplicer **matrix_a** og **matrix_b**, og tildel produktet
til **product_ab**. Beregn transponse af **product_ab**, og
få vist resultatet ved hjælp af funktionen print().

* Bekræft at transponse af **product_ab** er den samme
som **trans_ba**



In [35]:
transpose_a = matrix_a.T
print('A.T')
print(transpose_a)
print('A')
print(matrix_a)
print('A.T.T')
print(transpose_a.T)

A.T
[[0.7 1.7]
 [3.  2. ]]
A
[[0.7 3. ]
 [1.7 2. ]]
A.T.T
[[0.7 3. ]
 [1.7 2. ]]


In [36]:
trans_ba = matrix_b.T @ matrix_a.T
trans_ab = matrix_a.T @ matrix_b.T

product_ab = matrix_a @ matrix_b

In [37]:
product_ab.T

array([[ 6.7,  5.7],
       [10.4,  9.4]])

In [39]:
trans_ba

array([[ 6.7,  5.7],
       [10.4,  9.4]])

In [41]:
trans_ba == product_ab.T

array([[ True,  True],
       [ True,  True]])

#### Del 3.5
I matrixligningen, som vi så sidste gang, prøver vi at løse
for vektoren $\vec{x}$.


$A\vec{x} = \vec{b}$

Her multipliceres matrixen $A$ med vektoren $\vec{x}$, og vi har derfor brug for en måde at fjerne $A$.

Lad os se på identitetsmatricen, som vi kort så sidst i første
del i dette kursus. Som du kan huske, består den af 1er langs diagonalen og 0er ellers. Her ser vi en 2x2 identitetsmatrix som vi vil skrive som $I_2$:


$I_2 = 
  \begin{bmatrix}
    1 & 0\\
    0 & 1 \\
  \end{bmatrix}$

Når vi multiplicerer $I_2$ med en vektor, der indeholder 2 elementer, matcher den resulterende vektor den oprindelige vektor nøjagtigt:

$I_2\vec{x} = \vec{x}$

Dette skyldes, at hvert element i vektoren ganges nøjagtigt en gang med den
diagonale $1$ værdi i identitetsmatrixen:



Eksempel med tal: 
$$
  \begin{bmatrix}
    1 & 0 \\
    0 & 1 \\
  \end{bmatrix}
%
  \begin{bmatrix}
    3 \\
    2 \\
  \end{bmatrix}
 %
=
  \begin{bmatrix}
    1*3 + 0*2 \\
    0*3 + 1*2 \\
  \end{bmatrix}
%
=
  \begin{bmatrix}
    3 \\
    2 \\
  \end{bmatrix} 
$$

Generel brug: 
$$
  \begin{bmatrix}
    1 & 0 \\
    0 & 1 \\
  \end{bmatrix}
%
  \begin{bmatrix}
    x_1 \\
    x_2 \\
  \end{bmatrix}
 %
=
  \begin{bmatrix}
    1x_1 + 0x_2 \\
    0x_1 + 1x_2 \\
  \end{bmatrix}
%
=
  \begin{bmatrix}
    x_1 \\
    x_2 \\
  \end{bmatrix} 
$$

Hvis vi kan transformere matrix $A$ og konvertere den til identitetsmatrixen, er det kun løsningsvektoren $\vec{x}$ der vil blive tilbage. 

Lad os lige øve at arbejde med identitetsmatrix, før vi prøver at løse transformationen af $A$ til $I$.

Vi kan oprette en hvilken som helst identitetsmatrix ved hjælp af funktionen `numpy.identity()`. Denne funktion har kun 1 parameter, `n`, som specificerer den $n * n$ identitesmatrix, vi har brug for.



**Øvelse** 

* Generer $I_2$ og tildel til **i_2**
* Generer $I_3$ og tildel til **i_3**
* Generer en 3 * 3 matrix og tildel til **matrix_33** brug `np.random.rand(n,n)` for at generere en random matrix (sparer tid...)
* Generer en 2 * 3 matrix og tildel til **matrix_23**
* Multiplicer **i_3** med **matrix_33** og tildel til **identity_33**
* Multiplicer **i_2** med **matrix_23** og tildel til **identity_23**

**identity_33** burde matche **matrix_33** og **identity_23** burde matche **matrix_23**

In [45]:
i_2 = np.identity(2)
i_3 = np.identity(3)

matrix_33 = np.random.rand(3,3)
matrix_23 = np.random.rand(2,3)

identity_33 = i_3 @ matrix_33
identity_23 = i_2 @ matrix_23

In [46]:
identity_33 == matrix_33

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [47]:
identity_23 == matrix_23

array([[ True,  True,  True],
       [ True,  True,  True]])

#### Del 3.6

Nu ved vi lidt mere om identitetsmatricen og kan overveje hvordan vi annullerer
koefficientmatrixen $A$. Eller sagt på en anden måde: Vi vil prøve at transformere $A$ til identitetsmatricen $I$. Dette gøres ved at multiplicere den **inverse** matrix med matricen. 



En invers matrix svarer til ideen om multiplikativ invers. Hvis vi, for eksempel, vil løse $x$ i ligningen $5x = 10$. For at gøre dette, har vi
brug for at multiplicere begge sider med den multiplikative inverse af $5$, som er $5^{-1}$ (eller $1/5$):

$5^{-1}*5x = 5^{-1} * 10$

Det omvendte af $5$ forvandler det til $1$ og efterlader os med løsningen: $x = 2$. For at løse for vektoren $\vec{x}$ i matrixligningen, er vi nødt til at gange begge sider med det inverse $A$:

$A^{-1}A\vec{x}=A^{-1}\vec{b}$

Dette kan simplificeres til $I\vec{x}=A^{-1}\vec{b}$, hvilket giver os formularen til at udregne løsningsvektoren:

$\vec{x} = A^{-1}\vec{b}$

Selvom vi bruger *inverse matrix* til at annullere bestemte i princippet på samme måde som når man bruger multiplikativ invers, er beregningen helt anderledes. Lad os forstå beregningen for det inverse af en 2 * 2 matrix.

Hvis $ A = 
  \begin{bmatrix}
    a & b\\
    c & d \\
  \end{bmatrix}$
så $A^{-1} = \frac{1}{ad-bc}\begin{bmatrix}
    d & -b\\
    -c & a \\
  \end{bmatrix}$


Udtrykket $ad - bc$ er kendt som **determinanten** og skrives ofte som
eller som $det(A) = ad - bc$ eller som $|A| = ad - bc$. Fordi vi deler med determinanten ved beregning af den inverse matrice, er en 2 x 2 matrix kun inverterbar, hvis determinanten ikke er lig med 0. 

I dette trin og det næste trin vil vi fokusere på
at finde den inverse matrix, når $A$ er en 2 x 2 matrix. Senere vil vi gennemgå, hvordan man beregner den inverse matrix til en højere dimensionel matrix (3 x 3 og derover).

Lad os implementere en invers matrix i Python før vi forsøger at løse matrixligningen. 


**Øvelse**

* Opret en funktion ved navn **matrix_inverse_two()**, der accepterer en 2 x
2 matrix, som en NumPy ndarray, og returnerer en invers matrix. Denne funktion
skal først beregne matrixens determinant.
  * Hvis determinanten er lig med 0, skal en fejl returneres.
  * Hvis determinanten ikke er lig med 0, skal denne funktion returnere invers matrix.
* Beregn det inverse af **matrix_a** ved hjælp af den funktion, du lige har skrevet og tildel resultatet til **inverse_a**.
* Multiplicer **inverse_a** med **matrix_a**, og tildel resultatet til **i_2**. Vis **i_2** ved hjælp af print() funktionen.



In [49]:
def matrix_inverse_two(M):
  det = M[0,0]*M[1,1] - M[0,1]*M[1,0]
  if det == 0:
    return ValueError('Determinant = 0 - nope dude!!!')
  else:
    return 1/det * np.array([[M[1,1],-M[0,1]],
                             [-M[1,0],M[0,0]]])

In [55]:
matrix_a = np.array([[1,2],
                     [3,4]])

In [56]:
inverse_a = matrix_inverse_two(matrix_a)

In [57]:
inverse_a @ matrix_a

array([[1., 0.],
       [0., 1.]])

In [59]:
np.linalg.inv(matrix_a) @ matrix_a

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

#### Del 3.7
Nu hvor vi ved, hvordan vi beregner den inverse matrix, kan vi løse vores system ved hjælp af matrixligning $A\vec{x} = \vec{b}$ som nedenfor.
 
$$
  \begin{bmatrix}
    300 & -1 \\
    400 & -1 \\
  \end{bmatrix}
%
  \begin{bmatrix}
    x_1 \\
    x_2\\
  \end{bmatrix}
 %
=
  \begin{bmatrix}
    -2500 \\
    -500 \\
  \end{bmatrix} 
$$

Vi starter med at gange med $A^{-1}$ på begge sider:

$$
  \begin{bmatrix}
    300 & -1 \\
    400 & -1 \\
  \end{bmatrix}
^{-1}
%
  \begin{bmatrix}
    300 & -1 \\
    400 & -1 \\
  \end{bmatrix}
%
   \begin{bmatrix}
    x_1\\
    x_2 \\
  \end{bmatrix}
=
  \begin{bmatrix}
    300 & -1 \\
    400 & -1 \\
  \end{bmatrix}
^{-1}
%
  \begin{bmatrix}
    -2500 \\
    -500 \\
  \end{bmatrix} 
$$

Dette kan skrives som :

$$   
\begin{bmatrix}
    x_1\\
    x_2 \\
  \end{bmatrix}
=
  \begin{bmatrix}
    300 & -1 \\
    400 & -1 \\
  \end{bmatrix}
^{-1}
%
  \begin{bmatrix}
    -2500 \\
    -500 \\
  \end{bmatrix} 
$$


Lad os afslutte det sidste trin i Python. For at beregne det inverse af en NumPy ndarray, kan vi bruge funktionen **numpy.linalg.inv()**.

**Øvelse**
* Afslut beregning af ligningen, og tildel løsningsvektoren til **solution_x**:
* Vis **solution_x** ved hjælp af **print()** funktionen


In [63]:
A = np.array([[300, -1],
              [400, -1]])

b = np.array([-2500, -500])

np.linalg.inv(A) @ b

array([  20., 8500.])

#### Del 3.8
Før vi undersøger, hvordan man beregner den inverse matrix for fler-dimensionelle matricer, skal vi først dykke dybere ned i determinanten og introducere noget mere terminologi. Indtil videre har vi for det meste arbejdet med matricer, der indeholder det samme antal rækker og kolonner. Disse matricer er kendt som kvadratmatricer, og vi kan kun beregne determinanten og den inverse matrix for kvadratmatricer. Derudover kan vi kun beregne den inverse matrix af kvadratmatricer, når determinanten **ikke** er lig med 0.

For at finde determinanten for en fler-dimensionel kvadratmatrix skal vi bruge
den mere generelle form af determinanten. Den ser sådan ud:

$ det( 
  \begin{bmatrix}
    a & b & c\\
    d & e & f \\
    g & h & i
  \end{bmatrix}) = a* det
  (\begin{bmatrix}
    e & f\\
    h & i \\
  \end{bmatrix})
  - b*det(
  \begin{bmatrix}
    d & f\\
    g & i \\
  \end{bmatrix}) + c* det
  (\begin{bmatrix}
    d & e\\
    g & h \\
  \end{bmatrix})$




Determinanten for et fler-dimensionelt system er forbundet med at nedbryde den fulde
matrix til mindre matricer. Først vælger vi en række eller kolonne (der vælges  tit den første række). For den første værdi i den valgte række "skjuler" vi de værdier i den række (2. og 3. værdi i rækken) og i den tilsvarende kolonne (2. og 3. værdi i kolonnen), benyt resten af elementerne som den mindre matrix, og gang den skalære værdi med determinanten for den mindre matrix. Vi gentager dette for de resterende værdier i første række. 

Dette diagram hjælper med at illustrere processen bedre:

Her er et konkret eksempel: 

$ det( 
  \begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6 \\
    7 & 8 & 9
  \end{bmatrix}) = 1* det
  (\begin{bmatrix}
    5 & 6\\
    8 & 9 \\
  \end{bmatrix})
  - 2*det(
  \begin{bmatrix}
    4 & 6\\
    7 & 9 \\
  \end{bmatrix}) + 3* det
  (\begin{bmatrix}
    4 & 5\\
    7 & 8 \\
  \end{bmatrix})$

For at beregne determinanten i NumPy bruger vi funktionen **numpy.linalg.det()**. Vi overlader det til dig at læse [dokumentationen](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html) og lære, hvordan du bruger denne funktion. 

**Øvelse**
* Beregn determinanten for **matrix_22**, og tildel til **det_22**.
* Beregn determinanten for **matrix_33** og tildel til **det_33**


In [66]:
np.linalg.inv(matrix_33)

array([[ 7.20229989, 10.0978807 , -9.60899151],
       [ 1.26889898, -1.48320813,  0.45377546],
       [-4.4993281 , -4.28952496,  5.89221007]])

#### Del 3.9
For at beregne en invers matrix for en 3 * 3 eller større matrix, skal vi også arbejde med den mere generelle form af matrixens inverse ligning. Svarende til determinanten for fler-dimensionelle matricer fungerer den inverse matrix ved at generere mindre matricer, der er afhængige af positionen i matrixen. Her er et diagram, der beskriver den inverse matrix for en 3 * 3 matrix:




$ 
\begin{bmatrix}
    a & b & c\\
    d & e & f \\
    g & h & i
\end{bmatrix} ^{-1} = 
\frac{1}{det(\begin{bmatrix}
    a & b & c\\
    d & e & f \\
    g & h & i
\end{bmatrix})}
\begin{bmatrix}
    det(\begin{bmatrix}
    a & - & -\\ 
    - & e & f \\
    - & h & i \end{bmatrix})  
  & ... 
  & det(\begin{bmatrix}
    - & - & c\\
    d & e & - \\
    g & h & - \end{bmatrix}) \\
... & ... & ... \\
det(\begin{bmatrix}
    - & b & c\\ 
    - & e & f \\
    g & - & - \end{bmatrix})  
  & ... 
  & det(\begin{bmatrix}
    a & b & -\\
    d & e & - \\
    - & - & i \end{bmatrix}) \\
\end{bmatrix}
$

Selvom det er nyttigt at vide, hvordan man beregner det inverse på denne måde til fler-dimensionelle matricer, er mængden af omhyggelig aritmetik, du skal udføre i hånden, stor. Heldigvis, kan funktionen **numpy.linalg.inv()** arbejde med enhver n-dimensionel kvadratmatrix. 


I denne session lærte vi om de forskellige matrixoperationer, og hvordan man løser et lineært system, der er repræsenteret som en matrixligning ved hjælp af en invers matrix. I den næste session lærer vi forskellige måder,hvordan et løsningssæt kan repræsenteres på, og hvordan man beregner determinanten for en fler-dimensionel matrix.

# Om random seeds

man kan bruge random tal fra numpy og aligevel få de samme resultater hver gang hvis man bruger

`np.random.seed(42)`

In [83]:
np.random.seed(42)
np.random.rand(2,2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848]])

#### Opsummering: Matrix algebra


In [ ]:
# Brug NumPy til at multiplicere en matrix med en vektor:
matrix_a = np.asarray([
[0.7, 3, 9],
[1.7, 2, 9],
[0.7, 9, 2]
], dtype=np.float32)
vector_b = np.asarray([
[1], [2], [1]
], dtype=np.float32)
ab_product = np.dot(matrix_a, vector_b)

In [ ]:
# Brug NumPy til at transponere en matrix:
matrix_b = np.asarray([
[113, 3, 10],
[1, 0, 1],
], dtype=np.float32)
transpose_b = np.transpose(matrix_b)

In [ ]:
# generer inverse matrix med NumPy:
np.identity(3) # creates the 3x3 identity matrix 

In [ ]:
# Udregn den inverse matrix med NumPy:
matrix_c = np.asarray([
[30, -1],
[50, -1]
])
matrix_c_inverse = np.linalg.inv(matrix_c)

In [ ]:
# Udregn determinanten af en matrix med NumPy:
matrix_22 = np.asarray([
[8, 4],
[4, 2]
])
det_22 = np.linalg.det(matrix_22)

##### **Hovedkoncepter**
* Mange operationer, der kan udføres på vektorer, kan også udføres på matricer. Vi kan udføre følgende operationer med matricer:
  * Tilføje og fratrække matricer, der indeholder den samme mængde rækker og kolonner.
  * Multiplicere en matrix med en skalær værdi.
  * Multiplicere en matrix med en vektor og andre matricer. For at multiplicere med en vektor eller en anden matrix, skal antallet af kolonner matche med antallet af rækker in vektoren eller matricen. 
* At transponere en matrix, vender rundt på rækker og kolonner i en matrix. Matematisk, kan vi benytte notationen $A^T$ til at specificere transponeringsoperationen. 
* Identitetsmatricen ineholder værdien $1$ på diagonalen, og værdien $0$ på de resterende positioner. Identitetsmatricen er ofte repræsenteret ved $I_n$ hvor $n$ er antallet af rækker og kolonner. 
* når vi multiplicerer med en vilkårlig vektor indeholdende 2 elementer, vil den resulterende vektor matche originale vektor fuldstændig.  
* For at transformere $A$ til en identitetsmatrice $I$ i $A\vec{x} = \overrightarrow{b}$, multiplicerer vi begge sider med det inverse af matrix $A$. 
* Det inverse af en 2x2 matrix kan findes ved at bruge følgende formel: 
  * $ A = 
  \begin{bmatrix}
    a & b\\
    c & d \\
  \end{bmatrix}$
så $A^{-1} = \frac{1}{ad-bc}\begin{bmatrix}
    d & -b\\
    -c & a \\
  \end{bmatrix}$
* Hvis determinanten a en 2x2 matrix, eller $ad-bc$ er lig med 0, er matricen **ikke** inverterbar. Man kan udelukkende udregne determinanten og den inverse matrice for matricer der har den samme mængde rækker og kolonner. 
* for at udregne determinanten for andre 2x2 matricer, kan vi opdele den fulde matrice ud til mindre matricer. 
